[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_amm = "ARje6fToWBZ3ivJxZpi5CQg2XVkemTEGdZRAAqBkgaaX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/xpsolitesol/Turbin3/turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
