[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
nft_staking = "PeKuyGHjQYNqhDNP3Cj435MnwPmrufWSyB3FHetLZaM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/Turbin3/turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
